---
- name: Install CloudWatch Agent
  package:
    name: amazon-cloudwatch-agent
    state: present

- name: Create CloudWatch agent config directory
  file:
    path: /opt/aws/amazon-cloudwatch-agent/etc
    state: directory
    mode: '0755'

- name: Configure CloudWatch Agent
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    mode: '0644'
  notify: restart cloudwatch-agent

- name: Start and enable CloudWatch Agent
  systemd:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes

